// GENERATED CODE EDIT WITH CAUTION
// THIS FILE **WILL NOT** BE REGENERATED
// This file should be version controlled and can be manually edited.
part of 'schema.g.dart';

// While migrations are intelligently created, the difference between some commands, such as
// DropTable vs. RenameTable, cannot be determined. For this reason, please review migrations after
// they are created to ensure the correct inference was made.

// The migration version must **always** mirror the file name

const List<MigrationCommand> _migration_20250329202901_up = [
  InsertTable('Budget'),
  InsertTable('Wallet'),
  InsertTable('Category'),
  InsertTable('Transaction'),
  InsertTable('Recurrence'),
  InsertTable('SavingsWallet'),
  InsertTable('CreditWallet'),
  InsertTable('Profile'),
  InsertTable('BudgetTracking'),
  InsertTable('Currency'),
  InsertTable('Merchant'),
  InsertColumn('id', Column.varchar, onTable: 'Budget', unique: true),
  InsertForeignKey('Budget', 'Profile', foreignKeyColumn: 'profile_Profile_brick_id', onDeleteCascade: true, onDeleteSetDefault: false),
  InsertForeignKey('Budget', 'Category', foreignKeyColumn: 'category_Category_brick_id', onDeleteCascade: true, onDeleteSetDefault: false),
  InsertColumn('period', Column.integer, onTable: 'Budget'),
  InsertColumn('amount', Column.Double, onTable: 'Budget'),
  InsertColumn('start_date', Column.datetime, onTable: 'Budget'),
  InsertColumn('end_date', Column.datetime, onTable: 'Budget'),
  InsertColumn('created_at', Column.datetime, onTable: 'Budget'),
  InsertColumn('updated_at', Column.datetime, onTable: 'Budget'),
  InsertColumn('user_id', Column.varchar, onTable: 'Budget'),
  InsertColumn('category_id', Column.varchar, onTable: 'Budget'),
  InsertColumn('id', Column.varchar, onTable: 'Wallet', unique: true),
  InsertForeignKey('Wallet', 'Profile', foreignKeyColumn: 'profile_Profile_brick_id', onDeleteCascade: true, onDeleteSetDefault: false),
  InsertColumn('wallet_type', Column.integer, onTable: 'Wallet'),
  InsertColumn('name', Column.varchar, onTable: 'Wallet'),
  InsertColumn('description', Column.varchar, onTable: 'Wallet'),
  InsertColumn('base_currency', Column.varchar, onTable: 'Wallet'),
  InsertColumn('balance', Column.Double, onTable: 'Wallet'),
  InsertColumn('created_at', Column.datetime, onTable: 'Wallet'),
  InsertColumn('updated_at', Column.datetime, onTable: 'Wallet'),
  InsertColumn('exclude_from_total', Column.boolean, onTable: 'Wallet'),
  InsertColumn('archived', Column.boolean, onTable: 'Wallet'),
  InsertColumn('archived_at', Column.datetime, onTable: 'Wallet'),
  InsertColumn('archive_reason', Column.varchar, onTable: 'Wallet'),
  InsertColumn('user_id', Column.varchar, onTable: 'Wallet'),
  InsertColumn('id', Column.varchar, onTable: 'Category', unique: true),
  InsertForeignKey('Category', 'Profile', foreignKeyColumn: 'profile_Profile_brick_id', onDeleteCascade: true, onDeleteSetDefault: false),
  InsertColumn('parent_category_id', Column.varchar, onTable: 'Category'),
  InsertColumn('transaction_type', Column.integer, onTable: 'Category'),
  InsertColumn('name', Column.varchar, onTable: 'Category'),
  InsertColumn('icon', Column.varchar, onTable: 'Category'),
  InsertColumn('color', Column.varchar, onTable: 'Category'),
  InsertColumn('description', Column.varchar, onTable: 'Category'),
  InsertColumn('enabled', Column.boolean, onTable: 'Category'),
  InsertColumn('created_at', Column.datetime, onTable: 'Category'),
  InsertColumn('updated_at', Column.datetime, onTable: 'Category'),
  InsertColumn('user_id', Column.varchar, onTable: 'Category'),
  InsertColumn('id', Column.varchar, onTable: 'Transaction', unique: true),
  InsertForeignKey('Transaction', 'Profile', foreignKeyColumn: 'profile_Profile_brick_id', onDeleteCascade: true, onDeleteSetDefault: false),
  InsertForeignKey('Transaction', 'Wallet', foreignKeyColumn: 'wallet_Wallet_brick_id', onDeleteCascade: true, onDeleteSetDefault: false),
  InsertForeignKey('Transaction', 'Category', foreignKeyColumn: 'category_Category_brick_id', onDeleteCascade: false, onDeleteSetDefault: true),
  InsertColumn('transaction_type', Column.integer, onTable: 'Transaction'),
  InsertColumn('amount', Column.Double, onTable: 'Transaction'),
  InsertColumn('transaction_date', Column.datetime, onTable: 'Transaction'),
  InsertColumn('notes', Column.varchar, onTable: 'Transaction'),
  InsertColumn('image_attachment', Column.varchar, onTable: 'Transaction'),
  InsertForeignKey('Transaction', 'Recurrence', foreignKeyColumn: 'recurrence_Recurrence_brick_id', onDeleteCascade: false, onDeleteSetDefault: true),
  InsertColumn('transfer_id', Column.varchar, onTable: 'Transaction'),
  InsertColumn('created_at', Column.datetime, onTable: 'Transaction'),
  InsertColumn('updated_at', Column.datetime, onTable: 'Transaction'),
  InsertForeignKey('Transaction', 'Merchant', foreignKeyColumn: 'merchant_Merchant_brick_id', onDeleteCascade: false, onDeleteSetDefault: true),
  InsertColumn('user_id', Column.varchar, onTable: 'Transaction'),
  InsertColumn('wallet_id', Column.varchar, onTable: 'Transaction'),
  InsertColumn('category_id', Column.varchar, onTable: 'Transaction'),
  InsertColumn('recurrence_id', Column.varchar, onTable: 'Transaction'),
  InsertColumn('merchant_id', Column.varchar, onTable: 'Transaction'),
  InsertColumn('id', Column.varchar, onTable: 'Recurrence', unique: true),
  InsertForeignKey('Recurrence', 'Profile', foreignKeyColumn: 'profile_Profile_brick_id', onDeleteCascade: true, onDeleteSetDefault: false),
  InsertColumn('cron_string', Column.varchar, onTable: 'Recurrence'),
  InsertColumn('recurrence_type', Column.integer, onTable: 'Recurrence'),
  InsertColumn('description', Column.varchar, onTable: 'Recurrence'),
  InsertColumn('created_at', Column.datetime, onTable: 'Recurrence'),
  InsertColumn('updated_at', Column.datetime, onTable: 'Recurrence'),
  InsertColumn('user_id', Column.varchar, onTable: 'Recurrence'),
  InsertForeignKey('SavingsWallet', 'Wallet', foreignKeyColumn: 'wallet_Wallet_brick_id', onDeleteCascade: true, onDeleteSetDefault: false),
  InsertColumn('savings_goal', Column.Double, onTable: 'SavingsWallet'),
  InsertColumn('wallet_id', Column.varchar, onTable: 'SavingsWallet', unique: true),
  InsertForeignKey('CreditWallet', 'Wallet', foreignKeyColumn: 'wallet_Wallet_brick_id', onDeleteCascade: true, onDeleteSetDefault: false),
  InsertColumn('credit_limit', Column.Double, onTable: 'CreditWallet'),
  InsertColumn('state_day_of_month', Column.integer, onTable: 'CreditWallet'),
  InsertColumn('payment_due_day_of_month', Column.integer, onTable: 'CreditWallet'),
  InsertColumn('wallet_id', Column.varchar, onTable: 'CreditWallet', unique: true),
  InsertColumn('id', Column.varchar, onTable: 'Profile', unique: true),
  InsertColumn('fcm_token', Column.varchar, onTable: 'Profile'),
  InsertForeignKey('BudgetTracking', 'Transaction', foreignKeyColumn: 'transaction_Transaction_brick_id', onDeleteCascade: true, onDeleteSetDefault: false),
  InsertForeignKey('BudgetTracking', 'Budget', foreignKeyColumn: 'budget_Budget_brick_id', onDeleteCascade: true, onDeleteSetDefault: false),
  InsertColumn('amount', Column.Double, onTable: 'BudgetTracking'),
  InsertColumn('created_at', Column.datetime, onTable: 'BudgetTracking'),
  InsertColumn('updated_at', Column.datetime, onTable: 'BudgetTracking'),
  InsertColumn('transaction_id', Column.varchar, onTable: 'BudgetTracking'),
  InsertColumn('budget_id', Column.varchar, onTable: 'BudgetTracking'),
  InsertColumn('code', Column.varchar, onTable: 'Currency', unique: true),
  InsertColumn('name', Column.varchar, onTable: 'Currency'),
  InsertColumn('symbol', Column.varchar, onTable: 'Currency'),
  InsertColumn('created_at', Column.datetime, onTable: 'Currency'),
  InsertColumn('updated_at', Column.datetime, onTable: 'Currency'),
  InsertColumn('id', Column.varchar, onTable: 'Merchant', unique: true),
  InsertForeignKey('Merchant', 'Profile', foreignKeyColumn: 'profile_Profile_brick_id', onDeleteCascade: true, onDeleteSetDefault: false),
  InsertColumn('name', Column.varchar, onTable: 'Merchant'),
  InsertColumn('address', Column.varchar, onTable: 'Merchant'),
  InsertColumn('lat', Column.Double, onTable: 'Merchant'),
  InsertColumn('lng', Column.Double, onTable: 'Merchant'),
  InsertColumn('metadata', Column.varchar, onTable: 'Merchant'),
  InsertColumn('created_at', Column.datetime, onTable: 'Merchant'),
  InsertColumn('updated_at', Column.datetime, onTable: 'Merchant'),
  InsertColumn('user_id', Column.varchar, onTable: 'Merchant'),
  CreateIndex(columns: ['id'], onTable: 'Budget', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Wallet', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Category', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Transaction', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Recurrence', unique: true),
  CreateIndex(columns: ['wallet_id'], onTable: 'SavingsWallet', unique: true),
  CreateIndex(columns: ['wallet_id'], onTable: 'CreditWallet', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Profile', unique: true),
  CreateIndex(columns: ['code'], onTable: 'Currency', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Merchant', unique: true)
];

const List<MigrationCommand> _migration_20250329202901_down = [
  DropTable('Budget'),
  DropTable('Wallet'),
  DropTable('Category'),
  DropTable('Transaction'),
  DropTable('Recurrence'),
  DropTable('SavingsWallet'),
  DropTable('CreditWallet'),
  DropTable('Profile'),
  DropTable('BudgetTracking'),
  DropTable('Currency'),
  DropTable('Merchant'),
  DropColumn('id', onTable: 'Budget'),
  DropColumn('profile_Profile_brick_id', onTable: 'Budget'),
  DropColumn('category_Category_brick_id', onTable: 'Budget'),
  DropColumn('period', onTable: 'Budget'),
  DropColumn('amount', onTable: 'Budget'),
  DropColumn('start_date', onTable: 'Budget'),
  DropColumn('end_date', onTable: 'Budget'),
  DropColumn('created_at', onTable: 'Budget'),
  DropColumn('updated_at', onTable: 'Budget'),
  DropColumn('user_id', onTable: 'Budget'),
  DropColumn('category_id', onTable: 'Budget'),
  DropColumn('id', onTable: 'Wallet'),
  DropColumn('profile_Profile_brick_id', onTable: 'Wallet'),
  DropColumn('wallet_type', onTable: 'Wallet'),
  DropColumn('name', onTable: 'Wallet'),
  DropColumn('description', onTable: 'Wallet'),
  DropColumn('base_currency', onTable: 'Wallet'),
  DropColumn('balance', onTable: 'Wallet'),
  DropColumn('created_at', onTable: 'Wallet'),
  DropColumn('updated_at', onTable: 'Wallet'),
  DropColumn('exclude_from_total', onTable: 'Wallet'),
  DropColumn('archived', onTable: 'Wallet'),
  DropColumn('archived_at', onTable: 'Wallet'),
  DropColumn('archive_reason', onTable: 'Wallet'),
  DropColumn('user_id', onTable: 'Wallet'),
  DropColumn('id', onTable: 'Category'),
  DropColumn('profile_Profile_brick_id', onTable: 'Category'),
  DropColumn('parent_category_id', onTable: 'Category'),
  DropColumn('transaction_type', onTable: 'Category'),
  DropColumn('name', onTable: 'Category'),
  DropColumn('icon', onTable: 'Category'),
  DropColumn('color', onTable: 'Category'),
  DropColumn('description', onTable: 'Category'),
  DropColumn('enabled', onTable: 'Category'),
  DropColumn('created_at', onTable: 'Category'),
  DropColumn('updated_at', onTable: 'Category'),
  DropColumn('user_id', onTable: 'Category'),
  DropColumn('id', onTable: 'Transaction'),
  DropColumn('profile_Profile_brick_id', onTable: 'Transaction'),
  DropColumn('wallet_Wallet_brick_id', onTable: 'Transaction'),
  DropColumn('category_Category_brick_id', onTable: 'Transaction'),
  DropColumn('transaction_type', onTable: 'Transaction'),
  DropColumn('amount', onTable: 'Transaction'),
  DropColumn('transaction_date', onTable: 'Transaction'),
  DropColumn('notes', onTable: 'Transaction'),
  DropColumn('image_attachment', onTable: 'Transaction'),
  DropColumn('recurrence_Recurrence_brick_id', onTable: 'Transaction'),
  DropColumn('transfer_id', onTable: 'Transaction'),
  DropColumn('created_at', onTable: 'Transaction'),
  DropColumn('updated_at', onTable: 'Transaction'),
  DropColumn('merchant_Merchant_brick_id', onTable: 'Transaction'),
  DropColumn('user_id', onTable: 'Transaction'),
  DropColumn('wallet_id', onTable: 'Transaction'),
  DropColumn('category_id', onTable: 'Transaction'),
  DropColumn('recurrence_id', onTable: 'Transaction'),
  DropColumn('merchant_id', onTable: 'Transaction'),
  DropColumn('id', onTable: 'Recurrence'),
  DropColumn('profile_Profile_brick_id', onTable: 'Recurrence'),
  DropColumn('cron_string', onTable: 'Recurrence'),
  DropColumn('recurrence_type', onTable: 'Recurrence'),
  DropColumn('description', onTable: 'Recurrence'),
  DropColumn('created_at', onTable: 'Recurrence'),
  DropColumn('updated_at', onTable: 'Recurrence'),
  DropColumn('user_id', onTable: 'Recurrence'),
  DropColumn('wallet_Wallet_brick_id', onTable: 'SavingsWallet'),
  DropColumn('savings_goal', onTable: 'SavingsWallet'),
  DropColumn('wallet_id', onTable: 'SavingsWallet'),
  DropColumn('wallet_Wallet_brick_id', onTable: 'CreditWallet'),
  DropColumn('credit_limit', onTable: 'CreditWallet'),
  DropColumn('state_day_of_month', onTable: 'CreditWallet'),
  DropColumn('payment_due_day_of_month', onTable: 'CreditWallet'),
  DropColumn('wallet_id', onTable: 'CreditWallet'),
  DropColumn('id', onTable: 'Profile'),
  DropColumn('fcm_token', onTable: 'Profile'),
  DropColumn('transaction_Transaction_brick_id', onTable: 'BudgetTracking'),
  DropColumn('budget_Budget_brick_id', onTable: 'BudgetTracking'),
  DropColumn('amount', onTable: 'BudgetTracking'),
  DropColumn('created_at', onTable: 'BudgetTracking'),
  DropColumn('updated_at', onTable: 'BudgetTracking'),
  DropColumn('transaction_id', onTable: 'BudgetTracking'),
  DropColumn('budget_id', onTable: 'BudgetTracking'),
  DropColumn('code', onTable: 'Currency'),
  DropColumn('name', onTable: 'Currency'),
  DropColumn('symbol', onTable: 'Currency'),
  DropColumn('created_at', onTable: 'Currency'),
  DropColumn('updated_at', onTable: 'Currency'),
  DropColumn('id', onTable: 'Merchant'),
  DropColumn('profile_Profile_brick_id', onTable: 'Merchant'),
  DropColumn('name', onTable: 'Merchant'),
  DropColumn('address', onTable: 'Merchant'),
  DropColumn('lat', onTable: 'Merchant'),
  DropColumn('lng', onTable: 'Merchant'),
  DropColumn('metadata', onTable: 'Merchant'),
  DropColumn('created_at', onTable: 'Merchant'),
  DropColumn('updated_at', onTable: 'Merchant'),
  DropColumn('user_id', onTable: 'Merchant'),
  DropIndex('index_Budget_on_id'),
  DropIndex('index_Wallet_on_id'),
  DropIndex('index_Category_on_id'),
  DropIndex('index_Transaction_on_id'),
  DropIndex('index_Recurrence_on_id'),
  DropIndex('index_SavingsWallet_on_wallet_id'),
  DropIndex('index_CreditWallet_on_wallet_id'),
  DropIndex('index_Profile_on_id'),
  DropIndex('index_Currency_on_code'),
  DropIndex('index_Merchant_on_id')
];

//
// DO NOT EDIT BELOW THIS LINE
//

@Migratable(
  version: '20250329202901',
  up: _migration_20250329202901_up,
  down: _migration_20250329202901_down,
)
class Migration20250329202901 extends Migration {
  const Migration20250329202901()
    : super(
        version: 20250329202901,
        up: _migration_20250329202901_up,
        down: _migration_20250329202901_down,
      );
}
