/// Flutter icons FeliCashIcons
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FeliCashIcons
///      fonts:
///       - asset: fonts/FeliCashIcons.ttf
///
///
///
library;

import 'package:flutter/widgets.dart';

/// The FeliCash custom icons set
class FeliCashIcons {
  FeliCashIcons._();

  static const _kFontFam = 'FeliCashIcons';
  static const String _kFontPkg = 'app_ui';

  /// The magic star for AI
  static const IconData magic = IconData(
    0xe800,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );

  /// 3 magic stars for AI enhanced
  static const IconData magic_symbol = IconData(
    0xe801,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
}
