import 'package:flutter/material.dart';

/// {@template app_color_scheme}
/// Contains the app color scheme.
/// {@endtemplate}
abstract class AppColorScheme {
  /// App color scheme light
  static ColorScheme lightScheme() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff971e1b),
      surfaceTint: Color(0xffae2f29),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xffb93730),
      onPrimaryContainer: Color(0xffffddd9),
      secondary: Color(0xff933b01),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xffb3521b),
      onSecondaryContainer: Color(0xffffefe9),
      tertiary: Color(0xff952a0f),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xffb64225),
      onTertiaryContainer: Color(0xffffe3dc),
      error: Color(0xffba1a1a),
      onError: Color(0xffffffff),
      errorContainer: Color(0xffffdad6),
      onErrorContainer: Color(0xff93000a),
      surface: Color(0xfffcf8f8),
      onSurface: Color(0xff1c1b1b),
      onSurfaceVariant: Color(0xff59413e),
      outline: Color(0xff8d706d),
      outlineVariant: Color(0xffe0bfbb),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff313030),
      inversePrimary: Color(0xffffb4ab),
      primaryFixed: Color(0xffffdad6),
      onPrimaryFixed: Color(0xff410002),
      primaryFixedDim: Color(0xffffb4ab),
      onPrimaryFixedVariant: Color(0xff8d1515),
      secondaryFixed: Color(0xffffdbcc),
      onSecondaryFixed: Color(0xff351000),
      secondaryFixedDim: Color(0xffffb694),
      onSecondaryFixedVariant: Color(0xff7a2f00),
      tertiaryFixed: Color(0xffffdad2),
      onTertiaryFixed: Color(0xff3c0700),
      tertiaryFixedDim: Color(0xffffb4a2),
      onTertiaryFixedVariant: Color(0xff872105),
      surfaceDim: Color(0xffddd9d9),
      surfaceBright: Color(0xfffcf8f8),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfff6f3f2),
      surfaceContainer: Color(0xfff1edec),
      surfaceContainerHigh: Color(0xffebe7e7),
      surfaceContainerHighest: Color(0xffe5e2e1),
    );
  }

  /// App color scheme dark
  static ColorScheme darkScheme() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xffffb4ab),
      surfaceTint: Color(0xffae2f29),
      onPrimary: Color(0xff680003),
      primaryContainer: Color(0xff911612),
      onPrimaryContainer: Color(0xffffddd9),
      secondary: Color(0xffffb694),
      onSecondary: Color(0xff581e00),
      secondaryContainer: Color(0xff7a3500),
      onSecondaryContainer: Color(0xffffe0d5),
      tertiary: Color(0xffffb4a2),
      onTertiary: Color(0xff5c1500),
      tertiaryContainer: Color(0xff873018),
      onTertiaryContainer: Color(0xffffdcd3),
      error: Color(0xffffb4ab),
      onError: Color(0xff690005),
      errorContainer: Color(0xff93000a),
      onErrorContainer: Color(0xffffdad6),
      surface: Color(0xff1c1b1b),
      onSurface: Color(0xffe6e1e1),
      onSurfaceVariant: Color(0xffe0bfbb),
      outline: Color(0xffa98c89),
      outlineVariant: Color(0xff59413e),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xffe6e1e1),
      inversePrimary: Color(0xff971e1b),
      primaryFixed: Color(0xff911612),
      onPrimaryFixed: Color(0xffffddd9),
      primaryFixedDim: Color(0xff911612),
      onPrimaryFixedVariant: Color(0xffffddd9),
      secondaryFixed: Color(0xffb3521b),
      onSecondaryFixed: Color(0xffffe0d5),
      secondaryFixedDim: Color(0xffb3521b),
      onSecondaryFixedVariant: Color(0xffffe0d5),
      tertiaryFixed: Color(0xffb64225),
      onTertiaryFixed: Color(0xffffdcd3),
      tertiaryFixedDim: Color(0xffb64225),
      onTertiaryFixedVariant: Color(0xffffdcd3),
      surfaceDim: Color(0xff313030),
      surfaceBright: Color(0xff494545),
      surfaceContainerLow: Color(0xff313030),
      surfaceContainerLowest: Color(0xff262525),
      surfaceContainer: Color(0xff2b2a2a),
      surfaceContainerHigh: Color(0xff363535),
      surfaceContainerHighest: Color(0xff414040),
    );
  }
}
