import 'package:flutter/material.dart';

/// {@template app_color_scheme}
/// Contains the app color scheme.
/// {@endtemplate}
abstract class AppColorScheme {
  /// App color scheme light
  static ColorScheme lightScheme() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff1a1a1c),
      surfaceTint: Color(0xff5f5e60),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xff3a3a3c),
      onPrimaryContainer: Color(0xffceccce),
      secondary: Color(0xff516600),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xffccfc0e),
      onSecondaryContainer: Color(0xff415300),
      tertiary: Color(0xff025d20),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xff368441),
      onTertiaryContainer: Color(0xffffffff),
      error: Color(0xffba1a1a),
      onError: Color(0xffffffff),
      errorContainer: Color(0xffffdad6),
      onErrorContainer: Color(0xff410002),
      surface: Color(0xfffafafa),
      onSurface: Color(0xff1c1b1b),
      onSurfaceVariant: Color(0xff46464a),
      outline: Color(0xff77777b),
      outlineVariant: Color(0xffc7c6ca),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff313030),
      onInverseSurface: Color(0xfff4f0ef),
      inversePrimary: Color(0xffc8c6c8),
      primaryFixed: Color(0xffe4e2e4),
      onPrimaryFixed: Color(0xff1b1b1d),
      primaryFixedDim: Color(0xffc8c6c8),
      onPrimaryFixedVariant: Color(0xff474649),
      secondaryFixed: Color(0xffc4f400),
      onSecondaryFixed: Color(0xff161e00),
      secondaryFixedDim: Color(0xffdbdbdb),
      onSecondaryFixedVariant: Color(0xff3c4d00),
      tertiaryFixed: Color(0xffa3f6a6),
      onTertiaryFixed: Color(0xff002106),
      tertiaryFixedDim: Color(0xff88d98c),
      onTertiaryFixedVariant: Color(0xff00531b),
      surfaceDim: Color(0xffddd9d9),
      surfaceBright: Color(0xfffafafa),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xffF4F4F4),
      surfaceContainer: Color(0xffefefef),
      surfaceContainerHigh: Color(0xffe9e9e9),
      surfaceContainerHighest: Color(0xffe3e3e3),
    );
  }

  /// App color scheme dark
  static ColorScheme darkScheme() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xffffb4ab),
      surfaceTint: Color(0xffae2f29),
      onPrimary: Color(0xff680003),
      primaryContainer: Color(0xff911612),
      onPrimaryContainer: Color(0xffffddd9),
      secondary: Color(0xffffb694),
      onSecondary: Color(0xff581e00),
      secondaryContainer: Color(0xff7a3500),
      onSecondaryContainer: Color(0xffffe0d5),
      tertiary: Color(0xffffb4a2),
      onTertiary: Color(0xff5c1500),
      tertiaryContainer: Color(0xff873018),
      onTertiaryContainer: Color(0xffffdcd3),
      error: Color(0xffffb4ab),
      onError: Color(0xff690005),
      errorContainer: Color(0xff93000a),
      onErrorContainer: Color(0xffffdad6),
      surface: Color(0xff1c1b1b),
      onSurface: Color(0xffe6e1e1),
      onSurfaceVariant: Color(0xffe0bfbb),
      outline: Color(0xffa98c89),
      outlineVariant: Color(0xff59413e),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xffe6e1e1),
      inversePrimary: Color(0xff971e1b),
      primaryFixed: Color(0xff911612),
      onPrimaryFixed: Color(0xffffddd9),
      primaryFixedDim: Color(0xff911612),
      onPrimaryFixedVariant: Color(0xffffddd9),
      secondaryFixed: Color(0xffb3521b),
      onSecondaryFixed: Color(0xffffe0d5),
      secondaryFixedDim: Color(0xffb3521b),
      onSecondaryFixedVariant: Color(0xffffe0d5),
      tertiaryFixed: Color(0xffb64225),
      onTertiaryFixed: Color(0xffffdcd3),
      tertiaryFixedDim: Color(0xffb64225),
      onTertiaryFixedVariant: Color(0xffffdcd3),
      surfaceDim: Color(0xff313030),
      surfaceBright: Color(0xff494545),
      surfaceContainerLow: Color(0xff313030),
      surfaceContainerLowest: Color(0xff262525),
      surfaceContainer: Color(0xff2b2a2a),
      surfaceContainerHigh: Color(0xff363535),
      surfaceContainerHighest: Color(0xff414040),
    );
  }
}
