// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGsFOt6AxgxnX7-DWSykVp1TOkCWuH7pw',
    appId: '1:1079817934266:android:0b79facf743d14b617f983',
    messagingSenderId: '1079817934266',
    projectId: 'felicash-dev',
    storageBucket: 'felicash-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWSYPXUt1TL3YzFCBpMzoRKNaSzdTYAU8',
    appId: '1:1079817934266:ios:c5719a715d9a85de17f983',
    messagingSenderId: '1079817934266',
    projectId: 'felicash-dev',
    storageBucket: 'felicash-dev.firebasestorage.app',
    androidClientId: '1079817934266-4sjj78958ugfq3cf5c1lghnqd6ch4s5q.apps.googleusercontent.com',
    iosClientId: '1079817934266-p400jraa3357vu3v24qovi8o9k7238ja.apps.googleusercontent.com',
    iosBundleId: 'com.quimblelabs.felicash.dev',
  );

}