name: felicash_data_client
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.7.0
  flutter: ^3.29.0

dependencies:
  brick_offline_first_with_rest: ^4.0.1
  brick_offline_first_with_supabase: ^2.0.0
  brick_sqlite: ^4.0.1
  brick_supabase: ^2.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  sqflite: ^2.4.2
  supabase_flutter: ^2.8.4
  uuid: ^4.5.1

dev_dependencies:
  brick_offline_first_with_supabase_build: ^2.0.0
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0
